### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by tree1891** [gofabian/negotiation-middleware#4]
It shows below.
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: psr/http-message[1.0, 1.0.1].
    - Can only install one of: psr/http-message[1.0.1, 1.0].
    - Can only install one of: psr/http-message[1.0, 1.0.1].
    - gofabian/negotiation-middleware v0.1.2 requires psr/http-message 1.0 -> satisfiable by psr/http-message[1.0].
    - Installation request for gofabian/negotiation-middleware ^0.1.2 -> satisfiable by gofabian/negotiation-middleware[v0.1.2].
    - Installation request for psr/http-message (locked at 1.0.1) -> satisfiable by psr/http-message[1.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by gofabian** [comment]
Should be fixed with v0.1.3
